project_name: pusher
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - '386'
    ldflags: -s -w -X github.com/pusher/cli/config.version={{.Version}}
    tags:
      - osusergo
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - license: MIT
    description: "Pusher CLI provides access to Pusher platform functionality via a CLI!"
    formats:
      - deb
      - rpm
    homepage: "https://pusher.com/"
    maintainer: "Pusher <support@pusher.com>"
    vendor: Pusher
# brews:
#  - description: "Pusher CLI!"
#    tap:
#      name: homebrew-brew
#      owner: pusher
#    homepage: "https://pusher.com/"

