# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: pusher
builds:
- env:
  - CGO_ENABLED=0
build:
  binary: pusher
  goos:
    - windows
    - darwin
    - linux
    - freebsd
  goarch:
    - amd64
  ldflags: -s -w -X github.com/pusher/cli/config.version={{.Version}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  license: MIT
  description: "Pusher CLI provides access to Pusher platform functionality via a CLI!"
  formats:
    - deb
    - rpm
  homepage: "https://pusher.com/"
  maintainer: "Kevin <kevin.norman@pusher.com>"
  vendor: Pusher
brew:
  description: "Pusher CLI!"
  github:
    name: homebrew-brew
    owner: pusher
  homepage: "https://pusher.com/"
  
